// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6v7aBIQqA3jeUqq0kp-7y2pdz3Y8fNQ8',
    appId: '1:841347468762:web:d1a9834de21c1ef16084e3',
    messagingSenderId: '841347468762',
    projectId: 'flutter-study-app-d83ba',
    authDomain: 'flutter-study-app-d83ba.firebaseapp.com',
    storageBucket: 'flutter-study-app-d83ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuEb6e05E-UtOpam0PB0VXbrVIg7s6aqE',
    appId: '1:841347468762:android:55c65dcc55a5a92d6084e3',
    messagingSenderId: '841347468762',
    projectId: 'flutter-study-app-d83ba',
    storageBucket: 'flutter-study-app-d83ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt_e5bGI9mFm8ZKK8GCcfaniVXoSVQRmE',
    appId: '1:841347468762:ios:9685b726473983ec6084e3',
    messagingSenderId: '841347468762',
    projectId: 'flutter-study-app-d83ba',
    storageBucket: 'flutter-study-app-d83ba.appspot.com',
    iosClientId: '841347468762-81tgqte5bbatvmdp44lbajemjbt6j0fd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt_e5bGI9mFm8ZKK8GCcfaniVXoSVQRmE',
    appId: '1:841347468762:ios:9685b726473983ec6084e3',
    messagingSenderId: '841347468762',
    projectId: 'flutter-study-app-d83ba',
    storageBucket: 'flutter-study-app-d83ba.appspot.com',
    iosClientId: '841347468762-81tgqte5bbatvmdp44lbajemjbt6j0fd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );
}
